trigger:
  branches:
    include:
      - master
      - develop

variables:
  - group: springboot-ci-example

resources:
  repositories:
  - repository: templates
    type: github
    name: GladsonBruno/azure-template-pipelines
    endpoint: GladsonBruno
    ref: 'refs/heads/master'

extends:
  template: /maven/azure-pipeline.yml@templates