trigger:
  branches:
    include:
      - master
#      - develop

variables:
  CI_REGISTRY: gladsonbruno
  CONTAINER_REGISTRY_SERVICE_CONNECTION_NAME: 'DockerHub'
  DOCKER_BUILD_CONTEXT_FOLDER: $(Build.SourcesDirectory)
  DOCKERFILE_PATH: $(Build.SourcesDirectory)/Dockerfile
  IMAGE_NAME: 'demo-api'
  POM_FILE_LOCATION: $(Build.SourcesDirectory)/pom.xml
  SONAR_CLOUD_SERVICE_CONNECTION_NAME: 'SonarCloud'

stages:
  - stage: build_stage
    displayName: "Build"
#    dependsOn: [ "validations_stage" ]
    condition: or(
      eq(variables['Build.SourceBranchName'], 'master'),
      eq(variables['Build.SourceBranchName'], 'develop'),
      contains(variables['Build.SourceBranch'], 'refs/heads/release/'),
      contains(variables['Build.SourceBranch'], 'refs/heads/hotfix/')
      )
    variables:
      APPLICATION_VERSION: 0.0.1
    jobs: 
      - job: build_job
        displayName: "Build"
        pool:
          vmImage: ubuntu-20.04
          demands:
            - java
        steps:
          - checkout: self
            fetchDepth: null

          - task: JavaToolInstaller@0
            displayName: "[Setup] Use JDK 17"
            inputs:
              versionSpec: 17
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'

          - script: |
              sudo apt-get install xmlstarlet
            displayName: "[Setup] Install Package xmlstarlet"

          - script: |
              xmlstarlet edit -L --update '/_:project/_:version' --value '$(APPLICATION_VERSION)' $(POM_FILE_LOCATION)
            displayName: "[Setup] Update project version"

          - task: Maven@3
            displayName: '[Build] Maven Package'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'package -Dmaven.test.skip=true'
              publishJUnitResults: false
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false

          - task: Docker@2
            displayName: 'Docker Login'
            inputs:
              containerRegistry: $(CONTAINER_REGISTRY_SERVICE_CONNECTION_NAME)
              command: 'login'

          - task: Docker@2
            displayName: '[DockerBuild] Docker Build version $(APPLICATION_VERSION)'
            inputs:
              command: build
              containerRegistry: $(CONTAINER_REGISTRY_SERVICE_CONNECTION_NAME)
              repository: $(CI_REGISTRY)/$(IMAGE_NAME)
              buildContext: $(DOCKER_BUILD_CONTEXT_FOLDER)
              Dockerfile: $(DOCKERFILE_PATH)
              tags: $(APPLICATION_VERSION)

          - task: Docker@2
            displayName: '[DockerBuild] Docker Push version $(APPLICATION_VERSION)'
            inputs:
              containerRegistry: $(CONTAINER_REGISTRY_SERVICE_CONNECTION_NAME)
              repository: $(CI_REGISTRY)/$(IMAGE_NAME)
              command: 'push'
              tags: $(APPLICATION_VERSION)

          - script: |
              wget https://github.com/aquasecurity/trivy/releases/download/v0.37.0/trivy_0.37.0_Linux-64bit.tar.gz
              tar -xf trivy_0.37.0_Linux-64bit.tar.gz
              mv trivy $(Agent.TempDirectory)/trivy_scanner
              chmod a+x $(Agent.TempDirectory)/trivy_scanner
            displayName: 'Download Trivy'

          - script: |
              $(Agent.TempDirectory)/trivy_scanner/trivy \
                -d image -f json -o $(Agent.TempDirectory)/image-scan-results.json $(CI_REGISTRY)/$(IMAGE_NAME):$(APPLICATION_VERSION)
            displayName: '[Trivy] Scan Container Image With Trivy'

          - task: Docker@2
            displayName: 'Docker Logout'
            inputs:
              containerRegistry: $(CONTAINER_REGISTRY_SERVICE_CONNECTION_NAME)
              command: 'logout'

      - job: scan_docker_image_job
        displayName: "Scan Docker Image Job"
        dependsOn: [ "build_job" ]
        pool:
          vmImage: ubuntu-20.04
          demands:
            - java
        steps:
          - checkout: self
            fetchDepth: null

          - task: Docker@2
            displayName: 'Docker Login'
            inputs:
              containerRegistry: $(CONTAINER_REGISTRY_SERVICE_CONNECTION_NAME)
              command: 'login'

          - script: |
              wget https://github.com/aquasecurity/trivy/releases/download/v0.37.0/trivy_0.37.0_Linux-64bit.tar.gz
              tar -xf trivy_0.37.0_Linux-64bit.tar.gz
              mv trivy $(Agent.TempDirectory)/trivy_scanner
              chmod a+x $(Agent.TempDirectory)/trivy_scanner
            displayName: 'Download Trivy'

          - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
            - powershell: |
                New-Item -Path 'templates\junit-container-vulnerabilities-template.tpl' -ItemType File -Force
                Set-Content 'templates\junit-container-vulnerabilities-template.tpl' '<?xml version="1.0" ?>
                        <testsuites>
                        {{- range . -}}
                        {{- $failures := len .Vulnerabilities }}
                            <testsuite tests="1" failures="{{ $failures }}" time="" name="{{  .Target }}">
                            {{- if not (eq .Type "") }}
                                <properties>
                                    <property name="type" value="{{ .Type }}"></property>
                                </properties>
                                {{- end -}}
                                {{ range .Vulnerabilities }}
                                <testcase classname="{{ .PkgName }}-{{ .InstalledVersion }}" name="[{{ .Vulnerability.Severity }}] {{ .VulnerabilityID }}" time="">
                                    <failure message={{escapeXML .Title | printf "%q" }} type="description">Vulnerability ID: {{escapeXML .VulnerabilityID | printf "%q" }}. &#xA;Package Name: {{escapeXML .PkgName | printf "%q" }}. &#xA;Version: {{escapeXML .InstalledVersion | printf "%q" }}. &#xA;Description: {{escapeXML .Description | printf "%q" }}. &#xA;Reference: {{escapeXML .PrimaryURL | printf "%q" }}. &#xA;</failure>
                                </testcase>
                            {{- end }}
                            </testsuite>
                        {{- end }}
                        </testsuites>'
              displayName: '[Trivy] Generating Container Vulnerabilities Junit Template'

          - script: |
              $(Agent.TempDirectory)/trivy_scanner/trivy \
                -d image -f json -o $(Agent.TempDirectory)/image-scan-results.json $(CI_REGISTRY)/$(IMAGE_NAME):$(APPLICATION_VERSION)
            displayName: '[Trivy] Scan Container Image With Trivy'

          - script: |
              $(Agent.TempDirectory)/trivy_download/trivy \
                --exit-code 0 \
                --format template \
                --output $(Agent.TempDirectory)/trivy-image-junit-report.xml \
                --template "@templates/junit-container-vulnerabilities-template.tpl" \
                $(CI_REGISTRY)/$(IMAGE_NAME):$(APPLICATION_VERSION)
            displayName: '[Trivy] Generating Container Scanning Junit Report'

          - task: Docker@2
            displayName: 'Docker Logout'
            inputs:
              containerRegistry: $(CONTAINER_REGISTRY_SERVICE_CONNECTION_NAME)
              command: 'logout'

          - task: PublishTestResults@2
            displayName: 'Publish Junit Test Results'
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/junit-report.xml'
              mergeTestResults: true
              failTaskOnFailedTests: false
              testRunTitle: 'Trivy Container Vulnerabilities'